---
name: Debian Base Image
version: dev
slug: debian-base
description: Docker Debian base images used by Home Assistant Community Apps.
url: https://github.com/hassio-addons/app-debian-base
arch:
  - aarch64
  - amd64
